config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "sessions", :sessions => "sessions",  :registrations => "registrations",  :confirmations => "confirmations"}
  
  as :user do 
    match 'signout' => 'sessions#destroy', :as => :signout, :via => Devise.mappings[:user].sign_out_via
    match "/user/invalid_confirmation" => "confirmations#invalid_confirmation", :via => [:get], as: :invalid_confirmation
    post '/sessions' => "sessions#create", :as => :sessions
    post '/sessions/register' => "sessions#register", :as => :registration
    post '/sessions/forgot' => "sessions#forgot", :as => :forgot_password
    get '/sessions/is_login' => "sessions#is_login", :as => :is_login
    get 'user/ask-for-confirmation' => "confirmations#ask_to_confirm", :via => [:get], as: :ask_to_confirm
  end 

  root 'pages#landing'
  
  resources :edutrains do 
    member do 
      post "register"
    end
    
    collection do 
      get "my_edutrain"
    end
  end
  
  resources :lounges do 
    collection do 
      get "profile"
      get "change_password"
      patch "update_password"
    end
  end
  
  resources :member do
    collection do 
      get "registration"
      get "validate" 
      get "registration/:form_id" => "member#form_type", as: "form_reg_type"
      get "download_user_file/:user_file_id" => "member#download_user_file"
      patch "update_education_history"
      patch "update_work_history"
      patch "update_my_certification"
      patch "update_my_files"
      delete "delete_education_history/:user_education_id" => "member#delete_education_history", as: "delete_member_education_history"
      delete "delete_work_history/:user_work_id" => "member#delete_work_history", as: "delete_member_work_history"
      delete "delete_my_certification/:user_certification_id" => "member#delete_my_certification", as: "delete_member_certification"
      delete "delete_my_files/:user_file_id" => "member#delete_my_file", as: "delete_member_file"
    end
  end
  
  resources :invoices do
    member do 
      get "confirmation"
      post "create_confirmation"
    end
  end

  

  namespace :admin do
    resources :dashboards
    resources :users do  
      member do 
        get "set_registration_date"
        post "create_registration_date"
      end
    end
    resources :user_registration_forms do 
      member do 
        get "cancel_reg_bills"
      end
    end
    resources :edutrains
    resources :user_registration_files
    resources :invoices do 
      member do 
        get "confirmation"
        post "create_confirmation"
        patch "cancel_confirmation"
      end
      
    end
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base 
  belongs_to :user
  has_one :invoice_confirmation
  has_many :invoice_items
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Admin::DashboardsController 
  before_filter :set_invoice , :except => [:index, :new, :create]
  
  def index
    @invoices = Invoice.all
  end
  
  def show
  end
  
  def confirmation
  end
  
  def create_confirmation  
    if params["invoice"]["is_finished"].to_s == "true"
      @invoice.update({"is_finished" => true, "finish_on" => Time.now, "finish_created_by_id" => current_user.id, "status_id" => 2})
      
      flash["notice"] = "Pembayaran #{@invoice.invoice_note_id} Telah Terkonfirmasi"
      
      if @invoice.invoice_type_id == 0
        @invoice.user.update({"status_stage" => 3, "member_status" => 1, :is_approved => true})
        redirect_to set_registration_date_admin_user_path(@invoice.user_id) and return
      end
    else
      flash["notice"] = "Data Konfirmasi Anda Telah Disimpan"
    end
    
    redirect_to admin_invoices_path
  end
  
  def cancel_confirmation
    if params["invoice_note"].present?
      if @invoice.update({"status_id" => 0, "is_confirmed" => false})
        invoice_log = InvoiceLog.new
        invoice_log.invoice_id = @invoice.id
        invoice_log.user_id = @invoice.user_id
        invoice_log.status_id = 0
        invoice_log.description = params["invoice_note"]
        
        if invoice_log.save
          flash["notice"] = "Konfirmasi Invoice #{@invoice.invoice_note_id} Telah Dibatalkan"
        else
          flash["notice"] = "Invoice Log Tidak Berhasil Dibuat, Konfirmasi Invoice #{@invoice.invoice_note_id} Telah Dibatalkan"
          redirect_to confirmation_admin_invoice_path(@invoice) and return
        end
      else
        flash["notice"] = "Invoice Tidak Bisa Di Batalkan. Silahkan Coba Kembali"
        redirect_to confirmation_admin_invoice_path(@invoice) and return
      end
    else
      flash["notice"] = "Silahkan Meninggalkan Pesan Untuk Melakukan Pembatalan"
      redirect_to confirmation_admin_invoice_path(@invoice) and return
    end
    redirect_to admin_invoices_path
  end
  
  def destroy
    if @invoice.destroy
      flash["notice"] = "Invoice berhasil Dihapus"
    else
      flash["notice"] = "Invoice Tidak berhasil Dihapus"
    end
    redirect_to admin_invoices_path
  end
 
  
  private
  
    def set_invoice
      @invoice = Invoice.find_by id: params[:id]
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController 
  before_filter :authenticate_user!
  before_filter :set_invoice, :except => [:index, :new, :create]
  
  def index
    @invoices = current_user.invoices
  end
  
  def show
  end
  
  def confirmation 
  end
  
  def create_confirmation
    if @invoice.invoice_confirmation.blank?
      invoice_confirmation = InvoiceConfirmation.new(invoice_confirmation_params)
      if invoice_confirmation.save
        @invoice.update({"is_confirmed" => true, "status_id" => 1})
        flash["notice"] = "Konfirmasi Telah Kami Terima Dan Sedang Di Proses"
      else
        flash["notice"] = "Terjadi Kesalahan Pada Saat Menginput Data. Silahkan Coba Kembali."
        redirect_to confirmation_invoice_path(@invoice) and return
      end
    else
      invoice_confirmation = @invoice.invoice_confirmation
      if invoice_confirmation.update(invoice_confirmation_params)
        @invoice.update({"is_confirmed" => true, "status_id" => 1})
        flash["notice"] = "Konfirmasi Telah Kami Terima Dan Sedang Di Proses"
      else
        flash["notice"] = "Terjadi Kesalahan Pada Saat Menginput Data. Silahkan Coba Kembali."
        redirect_to confirmation_invoice_path(@invoice) and return
      end
    end
    redirect_to invoices_path
  end
  
  private
    def set_invoice
      @invoice = Invoice.find_by id: params[:id]
    end
    
    def invoice_confirmation_params
      params.require(:invoice_confirmation).permit(:paid_on, :paid_by, :invoice_id, :description, :title, :payment_method_id, :payment_copy)
    end
    
end

app/views/admin/invoices/confirmation.haml
= content_for :script do
  = javascript_include_tag 'ckeditor/ckeditor.js' 
  :javascript
    $(document).ready(function(){ 
      if ($('textarea').length > 0) {
          var data = $('#invoice_note');          
          $.each(data, function(i) {
            CKEDITOR.replace(data[i].id, 
              {
                toolbar: [
                  { name: 'document', groups: [ 'mode', 'document', 'doctools' ], items: [ 'Source', '-', 'NewPage', 'Preview', 'Print', '-', 'Templates' ] },
                  { name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
                  { name: 'editing', groups: [ 'find', 'selection', 'spellchecker' ], items: [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
                  { name: 'forms', items: [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ] },
                  '/',
                  { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
                  { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
                  { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
                  { name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
                  '/',
                  { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
                  { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
                  { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
                  { name: 'others', items: [ '-' ] },
                ]
              }
            ); 
          });
      }
    });
.row
  .large-12.columns
    .row
      .large-12.columns
        %h2
          Konfirmasi Pembayaran
    %hr
    .row
      .large-12.columns
        .row
          .large-12.columns
            %h4
              Rincian Biaya
        .row
          .large-12.columns
            %table
              %thead
                %tr 
                  %th
                    Invoice ID
                  %th 
                    Title
                  %th
                    Jumlah
                  %th 
                    Biaya
                  %th
                    %strong
                      Total Biaya (Jumlah X Biaya)
              %tbody 
                %tr 
                  %td
                    = @invoice.invoice_note_id
                  %td
                    = @invoice.invoice_title
                  %td
                    = @invoice.total_amount
                  %td
                    = @invoice.total_price
                  %td
                    %strong
                      = @invoice.total_price 
        .row
          .large-12.columns
            %h4
              Konfirmasi Pembayaran
        .row
          .large-12.columns 
            .row
              .large-6.columns
                %label 
                  %strong
                    Pembayaran Dilakukan Pada Tanggal
              .large-6.columns
                = @invoice.invoice_confirmation.present? ? (@invoice.invoice_confirmation.paid_on.strftime("%d-%m-%Y") if @invoice.invoice_confirmation.paid_on.present? ) : "-" 
            .row
              .large-6.columns
                %label
                  %strong
                    Pembayaran Dilakukan Oleh
              .large-6.column
                = @invoice.invoice_confirmation.present? ? @invoice.invoice_confirmation.paid_by : "-" 
            .row
              .large-6.columns
                %label
                  %strong
                    Bukti Pembayaran
              .large-6.columns
                - if @invoice.invoice_confirmation.present?
                  - if @invoice.invoice_confirmation.payment_copy.present?
                    %a{"href" => @invoice.invoice_confirmation.payment_copy.url } Download
                  - else
                    %label
                      Tidak Tersedia
            .row
              .large-6.columns
                %label
                  %strong
                    Keterangan
              .large-6.columns
                = @invoice.invoice_confirmation.present? ? @invoice.invoice_confirmation.description : "-" 
.row
  .large-12.columns
    = form_tag create_confirmation_admin_invoice_path(@invoice) do 
      .row
        .large-12.columns
          = check_box_tag "invoice[is_finished]", false, false, :onclick=>"if($(this).is(':checked')){$(this).val(true);$(this).next().val(true)}else{$(this).val(false);$(this).next().val(false)};"
          = hidden_field_tag "invoice[is_finished]",false
          Saya yakin sepenuhnya, pembayaran telah diterima!
      .row
        .large-12.columns
          = submit_tag "lanjutkan", :class =>"columns small"
%hr
.row 
  .large-12.columns
    = form_tag cancel_confirmation_admin_invoice_path(@invoice), :method => "PATCH" do
      .row 
        .large-12.columns
          Apabila Anda Tidak Yakin, Silahkan Buat Pesan Di Bawah Ini Dan Tekan Tombol Pembatalan
      .row
        .large-12.columns
          = text_area_tag "invoice_note","", :required => true
      .row
        .large-12.columns
          =  submit_tag "batalkan", :class =>"columns small"

app/views/admin/invoices/index.haml
.row
  .large-12.columns
    .row
      .large-12.columns
        %h4
          Daftar Konfirmasi Pembayaran Yang Perlu Di Proses
    .row
      .large-12.columns
        %table
          %thead
            %tr 
              %th
                Invoice ID
              %th 
                Title 
              %th 
                Tanggal Pembayaran
              %th 
                Pembayaran Dilakukan Oleh
              %th 
                Status
              %th 
                Aksi
          %tbody
            - @invoices.each do |invoice|
              %tr 
                %td
                  = invoice.invoice_note_id
                %td
                  = invoice.invoice_title
                %td
                  = invoice.invoice_confirmation.present? ? (invoice.invoice_confirmation.paid_on.strftime("%d-%m-%Y") if invoice.invoice_confirmation.paid_on.present? ) : "-"
                %td
                  = invoice.invoice_confirmation.present? ? (invoice.invoice_confirmation.paid_by if invoice.invoice_confirmation.paid_by.present? ) : "-" 
                %td
                  = Preference::INVOICE_STATUS[invoice.status_id]
                %td
                  - if invoice.is_confirmed == true && invoice.status_id == 1
                    %a{"href" => confirmation_admin_invoice_path(invoice) } Memproses Konfirmasi Pembayaran
                  
                  %a{"href" => admin_invoice_path(invoice), "data-method" => "DELETE", :rel => "nofollow" } hapus