config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "sessions", :sessions => "sessions",  :registrations => "registrations",  :confirmations => "confirmations"}
  
  as :user do 
    match 'signout' => 'sessions#destroy', :as => :signout, :via => Devise.mappings[:user].sign_out_via
    match "/user/invalid_confirmation" => "confirmations#invalid_confirmation", :via => [:get], as: :invalid_confirmation
    post '/sessions' => "sessions#create", :as => :sessions
    post '/sessions/register' => "sessions#register", :as => :registration
    post '/sessions/forgot' => "sessions#forgot", :as => :forgot_password
    get '/sessions/is_login' => "sessions#is_login", :as => :is_login
    get 'user/ask-for-confirmation' => "confirmations#ask_to_confirm", :via => [:get], as: :ask_to_confirm
  end 

  root 'pages#landing'
  
  resources :edutrains do 
    member do 
      post "register"
    end
    
    collection do 
      get "my_edutrain"
    end
  end
  
  resources :lounges do 
    collection do 
      get "profile"
      get "change_password"
      patch "update_password"
    end
  end
  
  resources :member do
    collection do 
      get "registration"
      get "validate" 
      get "registration/:form_id" => "member#form_type", as: "form_reg_type"
      get "download_user_file/:user_file_id" => "member#download_user_file"
      patch "update_education_history"
      patch "update_work_history"
      patch "update_my_certification"
      patch "update_my_files"
      delete "delete_education_history/:user_education_id" => "member#delete_education_history", as: "delete_member_education_history"
      delete "delete_work_history/:user_work_id" => "member#delete_work_history", as: "delete_member_work_history"
      delete "delete_my_certification/:user_certification_id" => "member#delete_my_certification", as: "delete_member_certification"
      delete "delete_my_files/:user_file_id" => "member#delete_my_file", as: "delete_member_file"
    end
  end
  
  resources :invoices do
    member do 
      get "confirmation"
      post "create_confirmation"
    end
  end

  

  namespace :admin do
    resources :dashboards
    resources :users do  
      member do 
        get "set_registration_date"
        post "create_registration_date"
      end
    end
    resources :user_registration_forms do 
      member do 
        get "cancel_reg_bills"
      end
    end
    resources :edutrains
    resources :user_registration_files
    resources :invoices do 
      member do 
        get "confirmation"
        post "create_confirmation"
        patch "cancel_confirmation"
      end
      
    end
  end
end

app/controllers/lounges_controller.rb
class LoungesController < ApplicationController 
  before_filter :authenticate_user!
  
  def index
    @edutrains = Edutrain.where("is_publish IS TRUE").order("created_at DESC")
    @user_edutrains = []
    current_user.user_edutrains.each do |user_edu|
       @user_edutrains << user_edu.edutrain.id
    end
  end
  
  def profile
    @user_works = current_user.user_works.order("created_at DESC")
    @user_certifications = current_user.user_certifications.order("created_at DESC")
    @user_educations = current_user.user_educations.order("created_at DESC")
    render :layout => "blank"
  end
  
  def change_password
  end
  
  def update_password 
    
    if params["new_password"].present? && params["new_password_confirmation"].present?
    
      if current_user.valid_password?(params["current_password"])
        user = current_user
        if current_user.update({"password" => params["new_password"], "password_confirmation" => params["new_password_confirmation"]})
          sign_in( user, :bypass => true ) 
          flash["notice"] = "Password Anda Berhasil Diubah"
        else
          flash["notice"] = "Password Baru Anda Tidak Valid"
        end
      else
        flash["notice"] = "Password Anda Tidak Valid"
      end
    else
      flash["notice"] = "Password Baru Anda Tidak Boleh Kosing"
    end
    redirect_to change_password_lounges_path
  end
  
  private
end

app/views/lounges/change_password.haml
.row
  .large-12.columns
    .row
      .large-12.columns
        %h4
          Ganti Password
    .row.panel
      .large-12.columns
        %ol
          %li 
            Password Baru minimal 8 Karakter
    %br
    .row
      .large-12.columns
        = form_tag update_password_lounges_path , :method => "PATCH", :multipart => true do 
          .row
            .large-6.columns
              %label 
                %strong
                  Password
            .large-6.columns
              = password_field_tag "current_password"
          %hr
          .row
            .large-6.columns
              %label 
                %strong
                  Password baru
            .large-6.columns
              = password_field_tag "new_password"
          .row
            .large-6.columns
              %label 
                %strong
                  Konfirmasi Password Baru
            .large-6.columns
              = password_field_tag "new_password_confirmation"
          .row
            .large-12.columns
              = submit_tag "Perbaharui"

app/views/lounges/index.haml
.row
  .large-12.columns
  
    - if ( current_user.admin_note.present? ) && (current_user.status_stage == 2)
      .row
        .large-12.columns  
          .row
            .large-12.columns
              Anda Telah Didaftarkan Sebagai Anggota IKPI. Silahkan Melakukan Konfirmasi Pembayaran 
              %a{"href" => "#"}
                Disini
    - else 
      .row
        .large-12.columns
          %h2
            Selamat Datang Di IKPI Lounge
      .row
        .large-12.columns
          Anda Dapat Mendaftarkan Diri Anda Secara Online Disini Untuk Tergabung kedalam Keanggotaan IKPI.
      .row
        .large-12.columns
          Kedepannya, Kami Akan Memberikan Fasilitas Pelayanan Untuk Menunjang Profesi Anda Sebagai Konsultan Pajak.
           
      .row
        .large-12.columns
          %label
            %strong
              Segera Daftarkan Diri Anda! Untuk Menikmati Pelayanan Yang Kami Tawarkan Ini.
      %hr

.row
  .large-12.columns
    .row
      .large-12.columns
        %h4
          Event PPL 
    .row
      .large-12.columns
        = render "edutrains/listing"

app/views/lounges/profile.haml
= content_for :style do
  %link{:href => "http://fonts.googleapis.com/css?family=Old+Standard+TT", :rel => "stylesheet", :type => "text/css"}/
  :css
    h2 {
      font-family: 'Old Standard TT', serif;
      font-weight: bolder;
    }
    h4 {
      font-family: 'Old Standard TT', serif;
      font-weight: bolder;
      color: #899799;
    }
    #main-profile {
      background-color: #e9eaea;
      padding: 10px;
      margin: 10px;
    }
    .stuffy_gray {
      font-size: 12px;
      color: #899799;
    }
    .stuffy_gray.big{
      font-size: 16px;
      color: #899799;
    }
#main-profile.row
  .large-12.column 
    - unless current_user.is_approved
      .row
        .large-12.columns
          %label
            %strong
              Anda Belum Terdaftar Sebagai Anggota IKPI. 
              Kami Tidak Dapat Menampilkan Profil Anda.
    - else
      #user-profile.row.boxy{"style" => "margin: 15px;"}
        .large-4.columns.avatar
          - if current_user.avatar.present?
            %img{"src" => current_user.avatar.url, :alt => "Profile Picture"}
          - else
            %img{"src" => "/assets/profile_picture.png", :alt => "Profile Picture"}
        .large-8.columns.descriptions
          %p
            %h2
              = current_user.name
          %hr
          %p
            Sebagai
            =  current_user.current_workplace.work_place_position
            Di 
            =  current_user.current_workplace.work_place_name
          %p
            = current_user.ca_city
            ,
            = current_user.ca_province
          %p.member_dateline
            Masa Keanggotaan IKPI Sampai Dengan Tanggal
            %strong
              = current_user.registered_to.strftime("%y %B %Y %H:%M")
      #user-current-work.boxy{"style" => "margin: 15px;"}
        .large-12.columns
          .row
            .large-12.columns
              %h4
                Pekerjaan Saat Ini
          .row
            .large-12.columns
              %table
                %tbody
                  %tr 
                    %td
                      %strong
                        Nama Perusahaan
                    %td
                      = current_user.current_workplace.work_place_name
                  %tr 
                    %td
                      %strong
                        Kategori bisnis Perusahaan
                    %td
                      = Preference::JOB_BUSINESS_CAT[current_user.current_workplace.work_place_business_category_id]
                  %tr 
                    %td
                      %strong
                        Tipe Perusahaan
                    %td
                      = Preference::WORKPLACE_TYPE[current_user.current_workplace.work_place_type_id]
                  %tr 
                    %td
                      %strong
                        Jabatan Perusahaan
                    %td
                      = Preference::JOB_LEVEL[current_user.current_workplace.work_place_job_level_id]
                  %tr 
                    %td
                      %strong
                        Kategori Pekerjaan
                    %td
                      = Preference::JOB_FOI[current_user.current_workplace.work_place_field_of_interest_id]
                  %tr 
                    %td
                      %strong
                        Alamat Pekerjaan
                    %td
                      = current_user.current_workplace.work_place_address
                  %tr 
                    %td
                      %strong
                        Nomor Telepon Kantor
                    %td
                      = current_user.current_workplace.work_place_phone_no
                  %tr 
                    %td
                      %strong
                        Extension
                    %td
                      = current_user.current_workplace.work_place_phone_extension_no
                  %tr 
                    %td
                      %strong
                        Nomor Faximile Kantor
                    %td
                      = current_user.current_workplace.work_place_fax_no
      #user-work.row.boxy{"style" => "margin: 15px;"}
        .large-12.columns
          .row
            .large-12.columns
              %h4
                Pengalaman Pekerjaan
          .row
            .large-12.columns
              %br
              - @user_works.each do |work| 
                .row
                  .large-12.columns
                    %h5
                      = work.work_place_position
                      \-
                      = work.work_place_division
                .row
                  .large-12.columns
                    %h5
                      = work.work_place_name
                .row
                  .large-12.columns.stuffy_gray
                    = work.work_place_entry_date.present? ? work.work_place_entry_date.strftime("%B %Y") : "?"
                    \-
                    = work.work_place_out_date.present? ? work.work_place_out_date.strftime("%B %Y") : "?"
                    |
                    = work.work_place_address
                %hr
      #user-education.row.boxy{"style" => "margin: 15px;"}
        .large-12.columns
          .row
            .large-12.columns
              %h4
                Pendidikan
          .row
            .large-12.columns
              %br
              - @user_educations.each do |education| 
                .row
                  .large-12.columns
                    %h5
                      = education.education_institution_name
                      di 
                      = education.education_institution_city 
                .row
                  .large-12.columns.stuffy_gray.big
                    = Preference::EDU_STAGE[education.education_institution_stage_id]
                    |
                    = education.education_institution_course
                  
                .row
                  .large-12.columns.stuffy_gray
                    Tanggal Ijazah
                    \:
                    = education.date_of_diploma.strftime("%d %B %Y")
                %hr
      #user-certification.row.boxy{"style" => "margin: 15px;"}
        .large-12.columns
          .row
            .large-12.columns
              %h4
                Sertifikasi
          .row
            .large-12.columns
              %br
              - @user_certifications.each do |certification| 
                .row
                  .large-12.columns
                    %h5
                      = certification.certification_name
                      [ 
                      = certification.certification_no 
                      ]
                .row
                  .large-12.columns.stuffy_gray 
                    = certification.certification_date_of_graduation
                    |
                    = certification.certification_issuer
                .row
                  .large-12.columns
                    = certification.certification_description
                %hr