config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "sessions", :sessions => "sessions",  :registrations => "registrations",  :confirmations => "confirmations"}
  
  as :user do 
    match 'signout' => 'sessions#destroy', :as => :signout, :via => Devise.mappings[:user].sign_out_via
    match "/user/invalid_confirmation" => "confirmations#invalid_confirmation", :via => [:get], as: :invalid_confirmation
    post '/sessions' => "sessions#create", :as => :sessions
    post '/sessions/register' => "sessions#register", :as => :registration
    post '/sessions/forgot' => "sessions#forgot", :as => :forgot_password
    get '/sessions/is_login' => "sessions#is_login", :as => :is_login
    get 'user/ask-for-confirmation' => "confirmations#ask_to_confirm", :via => [:get], as: :ask_to_confirm
  end 

  root 'pages#landing'
  
  resources :edutrains do 
    member do 
      post "register"
    end
    
    collection do 
      get "my_edutrain"
    end
  end
  
  resources :lounges do 
    collection do 
      get "profile"
      get "change_password"
      patch "update_password"
    end
  end
  
  resources :member do
    collection do 
      get "registration"
      get "validate" 
      get "registration/:form_id" => "member#form_type", as: "form_reg_type"
      get "download_user_file/:user_file_id" => "member#download_user_file"
      patch "update_education_history"
      patch "update_work_history"
      patch "update_my_certification"
      patch "update_my_files"
      delete "delete_education_history/:user_education_id" => "member#delete_education_history", as: "delete_member_education_history"
      delete "delete_work_history/:user_work_id" => "member#delete_work_history", as: "delete_member_work_history"
      delete "delete_my_certification/:user_certification_id" => "member#delete_my_certification", as: "delete_member_certification"
      delete "delete_my_files/:user_file_id" => "member#delete_my_file", as: "delete_member_file"
    end
  end
  
  resources :invoices do
    member do 
      get "confirmation"
      post "create_confirmation"
    end
  end

  

  namespace :admin do
    resources :dashboards
    resources :users do  
      member do 
        get "set_registration_date"
        post "create_registration_date"
      end
    end
    resources :user_registration_forms do 
      member do 
        get "cancel_reg_bills"
      end
    end
    resources :edutrains
    resources :user_registration_files
    resources :invoices do 
      member do 
        get "confirmation"
        post "create_confirmation"
        patch "cancel_confirmation"
      end
      
    end
  end
end

app/models/edutrain.rb
class Edutrain < ActiveRecord::Base 
  has_many :user_edutrains 
  has_attached_file :image, :styles => { :medium => "350x350>", :thumb => "100x100>", :large => "650x650" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/edutrains_controller.rb
class Admin::EdutrainsController < Admin::DashboardsController
  before_filter :set_edutrain, :except => ["index", "new", "create"]
  
  def index
    @edutrains = Edutrain.order("created_at DESC")
  end
  
  def new
    @edutrain = Edutrain.new
  end
  
  def show
  end
  
  def edit
  end

  def create 
    @edutrain = Edutrain.new(edutrain_params)
    if @edutrain.save 
      flash["notice"] = "Data Berhasil Disimpan"
      redirect_to admin_edutrain_path(@edutrain) and return
    else
      flash["notice"] = "Terjadi Kesalahan Ketika Penyimpan Data."
      render :action => :new and return
    end
  end 
  
  def update 
    if @edutrain.update(edutrain_params)
      flash["notice"] = "Data Berhasil Diperbaharui"
      redirect_to admin_edutrain_path(@edutrain) and return
    else
      flash["notice"] = "Terjadi Kesalahan Ketika Penyimpan Data."
      render :edit => :new and return
    end
  end
  
  def destroy 
    if @edutrain.destroy
      flash["notice"] = "Data Berhasil Dihapus"
    else
      flash["notice"] = "Data Tidak Berhasil Dihapus"
    end
    
    redirect_to admin_edutrains_path
    
  end 
  
  private
    def set_edutrain
      @edutrain = Edutrain.find_by id: params["id"]
    end
  
    def edutrain_params
      params.require(:edutrain).permit(:is_publish, :price, :is_finish, :name, :edutrain_class_name, 
      :trainer_name, :start_time, :end_time, :edutrain_start_date, 
      :edutrain_end_date, :edutrain_place, :pcu_value, :edutrain_type_id,
      :edutrain_subscription_type_id, :rules_and_regulation, 
      :short_description, :description, :image_file_name, :image_content_type,
      :image_file_size, :image_updated_at)
    end
end

app/controllers/edutrains_controller.rb
class EdutrainsController < ApplicationController 
  before_filter :authenticate_user!, :except => [:show]
  before_filter :set_edutrain , :except => [:index, :new, :create]
  
  def index  
    @edutrains = Edutrain.where("is_publish IS TRUE").order("created_at DESC")
    @user_edutrains = []
    current_user.user_edutrains.each do |user_edu|
       @user_edutrains << user_edu.edutrain.id
    end
  end
  
  def show
  end
  
  def register 
    if params["user_edutrain"]["is_agreed"].to_s == "true"
      user_edutrain = UserEdutrain.new
      user_edutrain.user_id = current_user.id
      user_edutrain.edutrain_id = @edutrain.id
      if user_edutrain.save
        invoice = Invoice.new({"invoice_title" => "Pembayaran PPL - #{@edutrain.name}", "invoice_type_id" => 1, "status_id" => 0, "total_amount" => 1, "total_price" => @edutrain.price, "user_id" => current_user.id, "invoice_note_id" => "INV-"+current_user.generate_invoice_no.to_s})
        if invoice.save
          user_edutrain.update({"invoice_id" => invoice.id})
          flash["notice"] = "Anda Telah DiDaftarkan Ke PPL - #{@edutrain.name} - . Silahkan Melakukan Pembayaran Dengan Kode - #{invoice.invoice_note_id}"
        else
          user_edutrain.destroy
          flash["notice"] = "Terjadi Kesalahan Dalam Pendaftaran PPL. Silahkan Coba Kembali"
        end
      end
    else
      flash["notice"] = "Anda Belum Setuju Dengan Prasyarat PPL."
    end
    redirect_to edutrain_path(@edutrain)
  end
  
  private
  
    def set_edutrain
      @edutrain = Edutrain.find_by id: params["id"]
    end
end

app/views/edutrains/_listing.haml
%ul{"class" => "small-block-grid-2 medium-block-grid-3 large-block-grid-4"}
  - @edutrains.each do |edutrain|
    %li
      %ul{"class" => "pricing-table"}
        %li.description
          - if edutrain.image.present?
            %img{"src" => edutrain.image.url, "alt" => "Logo #{edutrain.name}"}
          - else
            %img{"src" => "", "alt" => "Logo"}
        %li.title
          = edutrain.name
        %li.description
          %h5
            Rp 
            = edutrain.price.present? ? edutrain.price : "0"
        %li{"class" => "bullet-item"}
          %label
            %strong
              Nama Kelas
          %br
          = edutrain.edutrain_class_name
        %li{"class" => "bullet-item"}
          %label
            %strong
              Tipe PPL
          %br
          = Preference::EDUTRAIN_TYPE[edutrain.edutrain_type_id.present? ? edutrain.edutrain_type_id : 0] 
        %li.description 
          = edutrain.short_description
        %li{"class" => "cta-button"}
          - if @user_edutrains.include?(edutrain.id)
            - get_user_edutrain(@user_edutrains.select{|n| n == edutrain.id}[0])
            - unless @user_edutrain.invoice.is_finished 
              %p
                Anda Sudah Terdaftar. Silahkan Melakukan Pembayaran Dan Konfirmasi
                %a{"href" => confirmation_invoice_path(@user_edutrain.invoice_id)} Disini
            - else
              %a{"class" => "button tiny", "href" => edutrain_path(edutrain)} Tinjau
          - else
            %a{"class" => "button tiny", "href" => edutrain_path(edutrain)} Tinjau

app/views/edutrains/_my_ppl.haml
%ul{"class" => "small-block-grid-2 medium-block-grid-3 large-block-grid-4"}
  - current_user.edutrains.each do |edutrain|
    %li
      %ul{"class" => "pricing-table"}
        %li.description
          - if edutrain.image.present?
            %img{"src" => edutrain.image.url, "alt" => "Logo #{edutrain.name}"}
          - else
            %img{"src" => "", "alt" => "Logo"}
        %li.title
          = edutrain.name
        %li.description
          %h5
            Rp 
            = edutrain.price.present? ? edutrain.price : "0"
        %li{"class" => "bullet-item"}
          %label
            %strong
              Nama Kelas
          %br
          = edutrain.edutrain_class_name
        %li{"class" => "bullet-item"}
          %label
            %strong
              Tipe PPL
          %br
          = Preference::EDUTRAIN_TYPE[edutrain.edutrain_type_id.present? ? edutrain.edutrain_type_id : 0] 
        %li.description 
          = edutrain.short_description
        %li{"class" => "cta-button"}
          - if @user_edutrains.include?(edutrain.id)
            - get_user_edutrain(@user_edutrains.select{|n| n == edutrain.id}[0])
            - unless @user_edutrain.invoice.is_finished 
              %p
                Anda Sudah Terdaftar. Silahkan Melakukan Pembayaran Dan Konfirmasi
                %a{"href" => confirmation_invoice_path(@user_edutrain.invoice_id)} Disini
            - else
              %a{"class" => "button tiny", "href" => edutrain_path(edutrain)} Tinjau
          - else
            %a{"class" => "button tiny", "href" => edutrain_path(edutrain)} Tinjau

app/views/edutrains/index.haml
.row
  .large-12.columns 
    .row
      .large-12.columns
        .row
          .large-12.columns
            %h7 
              Daftar PPL Anda
        %hr
        .row
          .large-12.columns
            = render "edutrains/my_ppl"
    %hr
    .row
      .large-12.columns
        .row
          .large-12.columns
            %h7 
              Daftar PPL Tersedia
        %hr
        .row
          .large-12.columns
            = render "edutrains/listing"

app/views/edutrains/show.haml
.row
  - if @edutrain.image.present?
    .large-12.columns
      %label
        %strong
          Logo
      %br
      %img{"src" => @edutrain.image.url, "alt" => "Logo Pelatihan"}
  - else
    .large-12.columns
      %label
        %strong
          Logo
.row
  .large-6.columns
    %label
      %strong
        Nama PPL
  .large-6.columns
    = @edutrain.name || ""
.row
  .large-6.columns
    %label
      %strong
        Biaya PPL
  .large-6.columns
    Rp 
    = @edutrain.price || ""
.row
  .large-6.columns
    %label
      %strong
        Nama PPL
  .large-6.columns
    =  @edutrain.edutrain_class_name || ""
.row
  .large-6.columns
    %label
      %strong
        Nama Trainer
  .large-6.columns
    = @edutrain.trainer_name || ""
.row
  .large-6.columns
    %label
      %strong
        Waktu Mulai
  .large-6.columns
    = @edutrain.start_time.present? ? @edutrain.start_time.strftime("%H:%M:%S") : "-"
.row
  .large-6.columns
    %label
      %strong
        Waktu Berakhir
  .large-6.columns
    = @edutrain.end_time.present? ? @edutrain.end_time.strftime("%H:%M:%S") : "-"
.row
  .large-6.columns
    %label
      %strong
        Tanggal Mulai
  .large-6.columns
    =  @edutrain.edutrain_start_date.present? ? @edutrain.edutrain_start_date.strftime("%d %B %Y") : "-"
.row
  .large-6.columns
    %label
      %strong
        Tanggal Berakhir
  .large-6.columns
    =  @edutrain.edutrain_end_date.present? ? @edutrain.edutrain_end_date.strftime("%d %B %Y") : "-"
.row
  .large-6.columns
    %label
      %strong
        Tempat Pertemuan
  .large-6.columns
    =  @edutrain.edutrain_place || ""
.row
  .large-6.columns
    %label
      %strong
        Nilai SKP
  .large-6.columns
    = @edutrain.pcu_value || ""
.row
  .large-6.columns
    %label
      %strong
        Tipe PPL
  .large-6.columns
    = Preference::EDUTRAIN_TYPE[@edutrain.edutrain_type_id.present? ? @edutrain.edutrain_type_id : 0]
.row
  .large-6.columns
    %label
      %strong
        Prasyarat Untuk Ikut Event Ini
  .large-6.columns
    =  @edutrain.rules_and_regulation || ""
.row
  .large-6.columns
    %label
      %strong
        Deskripsi Singkat
  .large-6.columns
    = @edutrain.short_description || ""
.row
  .large-6.columns
    %label
      %strong
        Deskripsi 
  .large-6.columns
    = @edutrain.description || ""
- if current_user
  .row
    .large-6.columns
      - if current_user.edutrain_ids.include?(@edutrain.id)
        .row
          .large-12.columns
            Anda Telah Mengambil PPL Ini. Silahkan Menggunakan Kode Invoice [
            = user_edutrain_invoice(current_user, @edutrain)
            ]
      - else
        .row
          .large-12.columns
            = form_tag register_edutrain_path(@edutrain), :method => "POST" do 
              .row
                .large-12.columns
                  = check_box_tag "user_edutrain[is_agreed]", false, false, :onclick => "if($(this).is(':checked')){$(this).val(true);$(this).next().val(true);}else{$(this).val(false);$(this).next().val(false);}"
                  = hidden_field_tag "user_edutrain[is_agreed]", false
                  Saya telah memenuhi prasyarat sesuai keterangan PPL di atas.
              .row
                .large-12.columns
                  = submit_tag "Daftar", :class => "button small"