config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "sessions", :sessions => "sessions",  :registrations => "registrations",  :confirmations => "confirmations"}
  
  as :user do 
    match 'signout' => 'sessions#destroy', :as => :signout, :via => Devise.mappings[:user].sign_out_via
    match "/user/invalid_confirmation" => "confirmations#invalid_confirmation", :via => [:get], as: :invalid_confirmation
    post '/sessions' => "sessions#create", :as => :sessions
    post '/sessions/register' => "sessions#register", :as => :registration
    post '/sessions/forgot' => "sessions#forgot", :as => :forgot_password
    get '/sessions/is_login' => "sessions#is_login", :as => :is_login
    get 'user/ask-for-confirmation' => "confirmations#ask_to_confirm", :via => [:get], as: :ask_to_confirm
  end 

  root 'pages#landing'
  
  resources :edutrains do 
    member do 
      post "register"
    end
    
    collection do 
      get "my_edutrain"
    end
  end
  
  resources :lounges do 
    collection do 
      get "profile"
      get "change_password"
      patch "update_password"
    end
  end
  
  resources :member do
    collection do 
      get "registration"
      get "validate" 
      get "registration/:form_id" => "member#form_type", as: "form_reg_type"
      get "download_user_file/:user_file_id" => "member#download_user_file"
      patch "update_education_history"
      patch "update_work_history"
      patch "update_my_certification"
      patch "update_my_files"
      delete "delete_education_history/:user_education_id" => "member#delete_education_history", as: "delete_member_education_history"
      delete "delete_work_history/:user_work_id" => "member#delete_work_history", as: "delete_member_work_history"
      delete "delete_my_certification/:user_certification_id" => "member#delete_my_certification", as: "delete_member_certification"
      delete "delete_my_files/:user_file_id" => "member#delete_my_file", as: "delete_member_file"
    end
  end
  
  resources :invoices do
    member do 
      get "confirmation"
      post "create_confirmation"
    end
  end

  

  namespace :admin do
    resources :dashboards
    resources :users do  
      member do 
        get "set_registration_date"
        post "create_registration_date"
      end
    end
    resources :user_registration_forms do 
      member do 
        get "cancel_reg_bills"
      end
    end
    resources :edutrains
    resources :user_registration_files
    resources :invoices do 
      member do 
        get "confirmation"
        post "create_confirmation"
        patch "cancel_confirmation"
      end
      
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :unhashed_password

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
         
  has_many :user_certifications
  has_many :user_edutrains
  has_many :edutrains, :through => :user_edutrains
  has_many :user_educations
  has_many :user_files
  has_many :user_registration_files, :through => :user_files
  has_many :user_works
  has_many :user_pcus
  
  has_many :invoices
  has_attached_file :avatar, :styles => { :medium => "350x350>", :thumb => "100x100>", :large => "650x650" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  
  validates :id_card_no, presence: true
  validates :name, presence: true
  validates :mobile_phone_no, presence: true
  
  def edutrain_ids
    edutrains = self.edutrains.collect(&:id)
    edutrains
  end
  
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end
  
  def generate_password
    char_input = [('a'..'z'), ('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten
    char_password = (0...8).map { char_input[rand(char_input.length)] }.join
    char_password
  end
  
  def generate_invoice_no
    char_input = [(0..9)].map { |i| i.to_a }.flatten
    char_password = (0...10).map { char_input[rand(char_input.length)] }.join
    char_password
  end
  
  def current_workplace
    user_workplace = self.user_works.blank? ? UserWork.new : self.user_works.where("user_works.is_current IS TRUE").take
    user_workplace
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::DashboardsController

  load_and_authorize_resource
  
  def index
    @users =  User.joins(:roles).where("roles.name != 'admin'").order("created_at DESC")
  end
  
  def set_registration_date
    @user = User.find_by id: params["id"]
  end
  
  def create_registration_date
    @user = User.find_by id: params["id"]
    if @user.present?
      if params["start_date"].present? && params["end_date"].present? 
        if @user.update({"registered_from" => params["start_date"], "registered_to" => params["end_date"]})
          flash["notice"] = "Data Berhasil Disimpan"
          redirect_to admin_users_path and return
        else
          flash["notice"] = "Tidak Bisa Minyimpan Data Tanggal. Silahkan Coba Lagi" 
        end
      else
        flash["notice"] = "Tanggal Mulai Dan Berakhir Wajib Diisi." 
      end
    else
      flash["notice"] = "Tidak Bisa Mengatur Validasi Keanggotaan. Silahkan Coba Lagi"
    end
    redirect_to set_registration_date_admin_user_path(@user) and return
  end
  
end

app/views/admin/users/_certification.haml
.row
  .large-12
    .row
      .large-12.columns    
        .row
          .large-12.columns
            %label
              %strong
                Tanggal Lulus
            = text_field_tag "user_certification[certification_date_of_graduation]", ""
        .row
          .large-12.columns
            %label
              %strong
                Nama Sertifikasi
            = text_field_tag "user_certification[certification_name]", ""
        .row
          .large-12.columns
            %label
              %strong
                Nomor Sertifikasi
            = text_field_tag "user_certification[certification_no]", ""
        .row
          .large-12.columns
            %label
              %strong
                Penyelenggara
            = text_field_tag "user_certification[certification_issuer]", ""  

app/views/admin/users/_education.haml
.row
  .large-12
    .row
      .large-12.columns 
        .row
          .large-6.columns
            %label
              %strong 
                Jenjang Pendidikan
          .large-6.columns
            = select_tag "user_education[education_institution_stage_id]", options_for_select(Preference::HEDU_STAGE)
        .row
          .large-6.columns
            %label
              %strong 
                Tanggal Ijazah
          .large-6.columns
            = date_field_tag "user_education[date_of_diploma]", ""
        .row
          .large-6.columns
            %label
              %strong 
                Nama Perguruan Tinggi
          .large-6.columns
            = text_field_tag "user_education[education_institution_name]", ""
        .row
          .large-6.columns
            %label
              %strong 
                Program Studi
          .large-6.columns
            = text_field_tag "user_education[education_institution_course]", ""
        .row
          .large-6.columns
            %label
              %strong 
                Kota Universitas
          .large-6.columns
            = text_field_tag "user_education[education_institution_city]", ""
         

app/views/admin/users/_files.haml
.row
  .large-12
    .row
      .large-6.columns    
        - UserRegistrationFile.all.each do |file|
          .row
            .large-12.columns
              %label
                %strong
                  = file.title
                  &nbsp;
                  = file.is_required? == true ?  "(Wajib)" : "(Jika Ada)"
              %label
                Apakah Ada?

app/views/admin/users/_profile.haml
.row
  .large-12
    .row
      .large-12.columns
        .row
          .large-6.columns
            %label
              %strong 
                Photo Profile
          .large-6.columns
            %img{"src" => current_user.avatar.url}
        .row
          .large-6.columns
            %label
              %strong 
                Domisili
          .large-6.columns
            = current_user.domicile
        .row
          .large-6.columns
            %label
              %strong 
                Nama Lengkap
          .large-6.columns
            = current_user.name
        .row
          .large-6.columns
            %label
              %strong 
                Nomor Kartu Penduduk
          .large-6.columns
            = current_user.id_card_no
        .row
          .large-6.columns
            %label
              %strong 
                Nomor NPWP
          .large-6.columns
            = current_user.tax_card_no
        .row
          .large-6.columns
            %label
              %strong 
                Gender
          .large-6.columns
            = current_user.gender
        .row
          .large-6.columns
            %label
              %strong 
                Agama 
          .large-6.columns
            = current_user.religion_id
        .row
          .large-6.columns
            %label
              %strong 
                Email
          .large-6.columns
            = current_user.email
        .row
          .large-6.columns
            %label
              %strong 
                Nomor Telephone Rumah
          .large-6.columns
            = current_user.phone_no
        .row
          .large-6.columns
            %label
              %strong 
                Nomor Handphone
          .large-6.columns
            = current_user.mobile_phone_no
        .row
          .large-6.columns
            %label
              %strong 
                Nomor Fax
          .large-6.columns
            = current_user.fax_no
      .large-12.columns
        .row
          .large-6.columns
            %h4
              Alamat Rumah
        %hr
        .row
          .large-6.columns
            %label
              %strong
                Alamat Lengkap
          .large-6.columns
            = current_user.ca_address
        .row
          .large-6.columns
            %label
              %strong
                RT
          .large-6.columns
            = current_user.ca_rt
        .row
          .large-6.columns
            %label
              %strong
                RW
          .large-6.columns
            = current_user.ca_rw
        .row
          .large-6.columns
            %label
              %strong
                Kelurahan
          .large-6.columns
            = current_user.ca_subdistrict
        .row
          .large-6.columns
            %label
              %strong
                Kecamatan
          .large-6.columns
            = current_user.ca_district
        .row
          .large-6.columns
            %label
              %strong
                Provinsi
          .large-6.columns
            = current_user.ca_province
        .row
          .large-6.columns
            %label
              %strong
                Kota
          .large-6.columns
            = current_user.ca_city
        .row
          .large-6.columns
            %label
              %strong
                Kode Pos
          .large-6.columns
            = current_user.ca_postal_code

app/views/admin/users/_work.haml
.row
  .large-12
    .row
      .large-12.columns  
        .row
          .large-12.columns
            %h4
              Data Pekerjaan Saat Ini
          .row
            .large-6.columns
              %label
                %strong 
                  Nama Perusahaan / Instansi
            .large-6.columns
              = current_user.current_workplace.present? ? current_user.current_workplace.work_place_name : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Jabatan
            .large-6.columns
              = current_user.current_workplace.present? ? current_user.current_workplace.work_place_position : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Alamat Kantor
            .large-6.columns
              = current_user.current_workplace.present? ? current_user.current_workplace.work_place_address : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Nomor Telepon
            .large-6.columns
              = current_user.current_workplace.present? ? current_user.current_workplace.work_place_phone_no : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Extension
            .large-6.columns
              = current_user.current_workplace.present? ? current_user.current_workplace.work_place_phone_extension_no : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Nomor Fax
            .large-6.columns
              = current_user.current_workplace.present? ? current_user.current_workplace.work_place_fax_no : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Job Level
            .large-6.columns
              = current_user.current_workplace.present? ? Preference::JOB_LEVEL[current_user.current_workplace.work_place_job_level_id] : "KOSONG" 
          .row
            .large-6.columns
              %label
                %strong 
                  Bidang Minat
            .large-6.columns
              = current_user.current_workplace.present? ? Preference::JOB_FOI[current_user.current_workplace.work_place_field_of_interest_id] : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Bidang Minat Lainnya
            .large-6.columns
              = current_user.current_workplace.present? ? Preference::JOB_OTH_FOI[current_user.current_workplace.work_place_other_foi_id] : "KOSONG" 
          .row
            .large-6.columns
              %label
                %strong 
                  Tipe Perusahaan/Instansi
            .large-6.columns
              = current_user.current_workplace.present? ? Preference::WORKPLACE_TYPE[current_user.current_workplace.work_place_type_id] : "KOSONG"
          .row
            .large-6.columns
              %label
                %strong 
                  Kategori Bisnis
            .large-6.columns
              = current_user.current_workplace.present? ? Preference::JOB_BUSINESS_CAT[current_user.current_workplace.work_place_business_category_id] : "KOSONG" 
              
      

app/views/admin/users/index.haml
.row
  .large-12.columns
    .row
      .large-12.columns
        %h2
          List Pengguna
    .row
      .large-12.columns
        %table
          %thead
            %tr
              %th
                Nama
              %th 
                Status
              %th 
                Keanggotaan Dimulai
              %th 
                Keanggotaan Berakhir
              %th 
                Sisa Hari (Keanggotaan)
              %th
                Aksi
          %tbody
            - @users.each do |user|
              %tr
                %td
                  = user.name || user.email
                %td
                  = user.confirmed? ? "Sudah Konfirmasi" : "Belum Konfirmasi"
                %td
                  = user.registered_from.present? ? user.registered_from.strftime("%d-%m-%Y %H:%M:%S") : ""
                %td
                  = user.registered_to.present? ? user.registered_to.strftime("%d-%m-%Y %H:%M:%S") : ""
                %td
                  = user.registered_to.present? ? "#{((user.registered_to - DateTime.now).to_i / 1.day)} Hari" : "-"
                %td
                  %a{"href" => admin_user_registration_form_path(user)} Formulir Pendaftaran
                  - if user.confirmed? and user.member_status == 1
                    %a{"href" => set_registration_date_admin_user_path(user)} Atur Validasi Tanggal Keanggotaan

app/views/admin/users/registration_form.haml
.row
  .large-12.columns
    .row
      .large-12.columns
        %h2
          Formulir Registrasi Anggota
    .row
      .lage-12.columns
        %div{"data-magellan-expedition" => "fixed"}
          %dl.sub-nav
            %dd{"data-magellan-arrival" => "profile"}
              %a{:href => "#profile"} Data Pribadi
            %dd{"data-magellan-arrival" => "education"}
              %a{:href => "#education"} Data Pendidikan
            %dd{"data-magellan-arrival" => "work"}
              %a{:href => "#work"} Data Pekerjaan
            %dd{"data-magellan-arrival" => "certification"}
              %a{:href => "#certification"} Data Sertifikasi
            %dd{"data-magellan-arrival" => "files"}
              %a{:href => "#files"} Berkas Yang Dibutuhkan
    %hr
    #profile.row{"data-magellan-destination" => "profile"}
      .large-12.columns
        .row
          .large-12.columns
            %h4
              Data Pribadi
        .row
          .large-12.columns
            = render("admin/users/profile")
    %hr
    #education.row{"data-magellan-destination" => "education"}
      .large-12.columns
        .row
          .large-12.columns
            %h4
              Data Pendidikan
        .row
          .large-12.columns
            = render("admin/users/education")
    #work.row{"data-magellan-destination" => "work"}
      .large-12.columns
        .row
          .large-12.columns
            %h4
              Data Pekerjaan
        .row
          .large-12.columns
            = render("admin/users/work")
    #certification.row{"data-magellan-destination" => "certification"}
      .large-12.columns
        .row
          .large-12.columns
            %h4
              Data Sertifikasi
        .row
          .large-12.columns
            = render("admin/users/certification")
    #files.row{"data-magellan-destination" => "files"}
      .large-12.columns
        .row
          .large-12.columns
            %h4
              Berkas Yang Dibutuhkan
        .row
          .large-12.columns
            = render("admin/users/files")

app/views/admin/users/set_registration_date.haml
= content_for :script do 
  :javascript
    $(document).ready(function(){
      $('#start_date').datetimepicker({
          dateFormat: 'dd-mm-yy',
          timeFormat: 'HH:mm:ss',
          changeMonth: true,
          changeYear: true
      });
      
      $('#end_date').datetimepicker({
          dateFormat: 'dd-mm-yy',
          timeFormat: 'HH:mm:ss',
          changeMonth: true,
          changeYear: true
      });
    });
.row
  .large-12.columns
    .row
      .large-12.columns
        %h4
          Atur Tanggal Keanggotaan
    %hr
    .row
      .large-12.columns
        = @user.name 
        %span
          - if @user.member_status == 1
            Telah Terkonfirmasi
    .row
      .large-12.columns
        Silahkan Input Tanggal Keanggotaan
    .row
      .large-12.columns
        = form_tag create_registration_date_admin_user_path(@user), :method => "POST" do 
          .row
            .large-6.columns
              %label
                %strong
                  Tanggal Mulai Keanggotaan
            .large-6.columns
              %label
                %strong
                  Tanggal Berakhir Keanggotaan
          .row
            .large-6.columns
              = text_field_tag "start_date", @user.registered_from.present? ? @user.registered_from.strftime("%d-%m-%Y %H:%M:%S") : "", :required =>  true
            .large-6.columns
              = text_field_tag "end_date", @user.registered_to.present? ? @user.registered_to.strftime("%d-%m-%Y %H:%M:%S") : "", :required =>  true
          .row
            .large-12.columns
              = submit_tag "Atur", :class => "columns small"
    